export const DESIGN_TOKEN_CONTRACT = {
  core: {
    color: {
      canvas: '#ffffff',
      surface1: '#f4f4f4',
      surface2: '#e0e0e0',
      ink: '#161616',
      inkMuted: '#525252',
      hairline: '#e0e0e0',
      primary: '#0f62fe',
      accent: '#e85d1c',
      success: '#24a148',
      warning: '#f1c21b',
      error: '#da1e28',
    },
    radius: {
      card: '8px',
      button: '4px',
      input: '4px',
    },
    typography: {
      sans: 'Inter, Noto Sans SC, Helvetica Neue, Arial, system-ui, sans-serif',
      mono: 'SFMono-Regular, Roboto Mono, Consolas, monospace',
    },
  },
  components: {
    buttonPrimaryBg: 'var(--color-primary)',
    buttonInquiryBg: 'var(--color-accent)',
    fieldBg: 'var(--color-surface-1)',
    fieldBorder: '#8d8d8d',
    fieldFocusRing: '0 0 0 2px var(--color-focus)',
    fieldHeightMd: 'var(--field-height-md)',
    fieldErrorBorder: 'var(--field-error-border)',
    requiredMarkerColor: 'var(--field-required-marker-color)',
    formFieldGroupGap: 'var(--form-field-group-gap)',
    errorSummaryBg: 'var(--form-error-summary-bg)',
    errorSummaryBorder: 'var(--form-error-summary-border)',
    statusSubmittingBg: 'var(--form-status-submitting-bg)',
    statusSuccessBg: 'var(--form-status-success-bg)',
    statusFailedBg: 'var(--form-status-failed-bg)',
    fileUploadSelectedBg: 'var(--file-upload-selected-bg)',
    fileUploadErrorBg: 'var(--file-upload-error-bg)',
    conditionalFieldTransitionDuration: 'var(--conditional-field-transition-duration)',
    cardBg: 'var(--color-canvas)',
    sidebarBg: 'var(--color-canvas)',
    mobileCtaBg: 'var(--color-canvas)',
    modalBg: 'var(--modal-bg)',
    drawerBg: 'var(--drawer-bg)',
  },
  layout: {
    containerPage: 'var(--container-page)',
    containerContent: 'var(--container-content)',
    containerReadable: 'var(--container-readable)',
    sectionPaddingBlock: 'var(--section-padding-block)',
    sectionPaddingInline: 'var(--section-padding-inline)',
    gridGapSm: 'var(--grid-gap-sm)',
    gridGapMd: 'var(--grid-gap-md)',
    gridGapLg: 'var(--grid-gap-lg)',
    contentMaxWidth: 'var(--content-max-width)',
    sidebarWidth: 'var(--sidebar-width)',
    stickyTopOffset: 'var(--sticky-top-offset)',
    headerHeight: 'var(--header-height)',
    mobileDockHeight: '72px',
  },
  state: {
    hoverBg: 'var(--state-hover-bg)',
    hoverBorder: 'var(--state-hover-border)',
    activeBg: 'var(--state-active-bg)',
    selectedBg: 'var(--state-selected-bg)',
    selectedBorder: 'var(--state-selected-border)',
    disabledOpacity: 'var(--state-disabled-opacity)',
    loadingOpacity: 'var(--state-loading-opacity)',
    invalidBg: 'var(--state-invalid-bg)',
    invalidBorder: 'var(--state-invalid-border)',
    validBg: 'var(--state-valid-bg)',
    validBorder: 'var(--state-valid-border)',
  },
  conversion: {
    inquiryCtaBg: 'var(--color-inquiry-cta)',
    inquiryCtaHoverBg: 'var(--color-inquiry-cta-hover)',
    inquiryCtaText: 'var(--conversion-inquiry-cta-text)',
    inquiryCtaShadow: 'var(--conversion-inquiry-cta-shadow)',
    stickySidebarWidth: 'var(--conversion-sticky-sidebar-width)',
    stickyTopOffset: 'var(--conversion-sticky-top-offset)',
    mobileDockHeight: 'var(--conversion-mobile-dock-height)',
    mobileDockBg: 'var(--conversion-mobile-dock-bg)',
    trustNoteColor: 'var(--conversion-trust-note-color)',
    trustIconColor: 'var(--conversion-trust-icon-color)',
    downloadGateWidth: 'var(--conversion-download-gate-width)',
    quoteCartWidth: 'var(--conversion-quote-cart-width)',
    quoteCartTriggerSize: 'var(--conversion-quote-cart-trigger-size)',
    quoteCartTriggerBottom: 'var(--conversion-quote-cart-trigger-bottom)',
    rfqProgressHeight: 'var(--conversion-rfq-progress-height)',
    rfqProgressTrackBg: 'var(--conversion-rfq-progress-track-bg)',
    rfqProgressActiveBg: 'var(--conversion-rfq-progress-active-bg)',
  },
  dataDisplay: {
    tableBg: 'var(--table-bg)',
    tableHeaderBg: 'var(--table-header-bg)',
    tableHeaderText: 'var(--table-header-text)',
    tableRowBorder: 'var(--table-row-border)',
    tableCellPaddingX: 'var(--table-cell-padding-x)',
    tableCellPaddingY: 'var(--table-cell-padding-y)',
    tableCellPaddingYCompact: 'var(--table-cell-padding-y-compact)',
    tableCellPaddingYRoomy: 'var(--table-cell-padding-y-roomy)',
    tableStickyBg: 'var(--table-sticky-bg)',
    tableErrorBg: 'var(--table-error-bg)',
    tableErrorText: 'var(--table-error-text)',
    procurementRowBg: 'var(--procurement-row-bg)',
    procurementRowLabelColor: 'var(--procurement-row-label-color)',
    procurementRowValueColor: 'var(--procurement-row-value-color)',
    badgeBg: 'var(--badge-bg)',
    chipBg: 'var(--chip-bg)',
    emptyStateBg: 'var(--empty-state-bg)',
    loadingStateBg: 'var(--loading-state-bg)',
  },
  media: {
    galleryAspect: 'var(--media-gallery-aspect)',
    productAspect: 'var(--media-product-aspect)',
    thumbnailSize: 'var(--media-thumbnail-size)',
    frameBg: 'var(--media-frame-bg)',
    frameBorder: 'var(--media-frame-border)',
    placeholderBg: 'var(--media-placeholder-bg)',
    placeholderIcon: 'var(--media-image-placeholder-icon)',
    documentPreviewBg: 'var(--media-document-preview-bg)',
    documentPreviewBorder: 'var(--media-document-preview-border)',
  },
  motion: {
    durationFast: 'var(--motion-duration-fast)',
    durationBase: 'var(--motion-duration-base)',
    durationSlow: 'var(--motion-duration-slow)',
    easeStandard: 'var(--motion-ease-standard)',
    easeEmphasized: 'var(--motion-ease-emphasized)',
    componentAccordionDuration: 'var(--motion-component-accordion-duration)',
    componentStepperDuration: 'var(--motion-component-stepper-duration)',
    componentToastDuration: 'var(--motion-component-toast-duration)',
  },
  layers: {
    tableSticky: 'var(--z-table-sticky)',
    dropdown: 'var(--z-dropdown)',
    sticky: 'var(--z-sticky)',
    header: 'var(--z-header)',
    dock: 'var(--z-dock)',
    drawer: 'var(--z-drawer)',
    modalBackdrop: 'var(--z-modal-backdrop)',
    modal: 'var(--z-modal)',
    toast: 'var(--z-toast)',
    overlayBg: 'var(--overlay-bg)',
    overlayBgSubtle: 'var(--overlay-bg-subtle)',
  },
  accessibility: {
    focusRing: 'var(--a11y-focus-ring)',
    focusOffset: 'var(--a11y-focus-offset)',
    minTouchTarget: '44px',
    errorText: 'var(--a11y-error-text)',
    errorBg: 'var(--a11y-error-bg)',
    errorAnnouncementRole: 'var(--a11y-error-announcement-role)',
    errorAnnouncementLive: 'var(--a11y-error-announcement-live)',
    reducedMotionDuration: 'var(--a11y-reduced-motion-duration)',
    contrastTextOnPrimary: 'var(--a11y-contrast-text-on-primary)',
    contrastTextOnAccent: 'var(--a11y-contrast-text-on-accent)',
  },
  brand: {
    primary: 'var(--brand-primary)',
    surface: 'var(--brand-surface)',
    fontSans: 'var(--brand-font-sans)',
    ink: 'var(--brand-ink)',
    protectedConversion: 'var(--brand-protected-conversion)',
    protectedFocus: 'var(--brand-protected-focus)',
    protectedError: 'var(--brand-protected-error)',
    protectedTokens: [
      '--color-inquiry-cta',
      '--color-error',
      '--a11y-focus-ring',
      '--conversion-inquiry-cta-bg',
      '--conversion-inquiry-cta-hover-bg',
    ],
  },
  emailTheme: {
    fontFamily: 'Arial, sans-serif',
    bodyText: '#2D2C2B',
    mutedText: '#666666',
    canvas: '#ffffff',
    ctaBg: '#e85d1c',
    ctaText: '#ffffff',
    preBg: '#f4f4f4',
    border: '#e0e0e0',
    radius: '6px',
    buttonPadding: '12px 24px',
    smallTextSize: '12px',
  },
  modules: {
    rfqWizard: {
      schema: 'RFQWizard.schema',
      state: 'RFQWizard.state',
      events: 'RFQWizard.events',
      validation: 'RFQWizard.validation',
      api: 'RFQWizard.api',
      analytics: 'RFQWizard.analytics',
      tokens: [
        '--module-rfq-stepper-bg',
        '--module-rfq-stepper-active-bg',
        '--module-rfq-panel-bg',
      ],
      stepperBg: 'var(--module-rfq-stepper-bg)',
      stepperActiveBg: 'var(--module-rfq-stepper-active-bg)',
      stepperCompleteBg: 'var(--module-rfq-stepper-complete-bg)',
      panelBg: 'var(--module-rfq-panel-bg)',
    },
    productConfigurator: {
      schema: 'ProductConfigurator.schema',
      state: 'ProductConfigurator.state',
      events: 'ProductConfigurator.events',
      validation: 'ProductConfigurator.validation',
      api: 'ProductConfigurator.api',
      analytics: 'ProductConfigurator.analytics',
      tokens: [
        '--module-configurator-option-bg',
        '--module-configurator-option-selected-bg',
      ],
      optionBg: 'var(--module-configurator-option-bg)',
      optionSelectedBg: 'var(--module-configurator-option-selected-bg)',
    },
    quoteCartManager: {
      schema: 'QuoteCartManager.schema',
      state: 'QuoteCartManager.state',
      events: 'QuoteCartManager.events',
      validation: 'QuoteCartManager.validation',
      api: 'QuoteCartManager.api',
      analytics: 'QuoteCartManager.analytics',
      tokens: [
        '--module-quote-cart-item-bg',
        '--conversion-quote-cart-width',
      ],
      itemBg: 'var(--module-quote-cart-item-bg)',
    },
    downloadCenter: {
      schema: 'DownloadCenter.schema',
      state: 'DownloadCenter.state',
      events: 'DownloadCenter.events',
      validation: 'DownloadCenter.validation',
      api: 'DownloadCenter.api',
      analytics: 'DownloadCenter.analytics',
      tokens: [
        '--module-download-center-card-bg',
        '--conversion-download-gate-width',
      ],
      cardBg: 'var(--module-download-center-card-bg)',
    },
    comparisonBuilder: {
      schema: 'ComparisonBuilder.schema',
      state: 'ComparisonBuilder.state',
      events: 'ComparisonBuilder.events',
      validation: 'ComparisonBuilder.validation',
      api: 'ComparisonBuilder.api',
      analytics: 'ComparisonBuilder.analytics',
      tokens: [
        '--module-comparison-highlight-bg',
        '--table-header-bg',
      ],
      highlightBg: 'var(--module-comparison-highlight-bg)',
    },
    leadScoringPanel: {
      schema: 'LeadScoringPanel.schema',
      state: 'LeadScoringPanel.state',
      events: 'LeadScoringPanel.events',
      validation: 'LeadScoringPanel.validation',
      api: 'LeadScoringPanel.api',
      analytics: 'LeadScoringPanel.analytics',
      tokens: [
        '--module-lead-score-hot-bg',
        '--module-lead-score-warm-bg',
        '--module-lead-score-qualified-bg',
      ],
      hotBg: 'var(--module-lead-score-hot-bg)',
      warmBg: 'var(--module-lead-score-warm-bg)',
      qualifiedBg: 'var(--module-lead-score-qualified-bg)',
    },
  },
  verticals: {
    machinery: {
      primary: '#0f62fe',
      accent: '#e85d1c',
      surfaceTint: '#f8fbff',
      specBg: '#f4f4f4',
      proofBg: '#edf5ff',
    },
    materials: {
      primary: '#007d79',
      accent: '#e85d1c',
      surfaceTint: '#f6fbfa',
      specBg: '#eef7f6',
      proofBg: '#defbe6',
    },
    'consumer-oem': {
      primary: '#0f62fe',
      accent: '#ff6f00',
      surfaceTint: '#fffaf2',
      specBg: '#f4f4f4',
      proofBg: '#fff1e0',
    },
  },
} as const;
