import { defineConfig, presetWind, presetIcons, transformerDirectives } from 'unocss';

export default defineConfig({
  presets: [presetWind(), presetIcons()],
  transformers: [transformerDirectives()],
  theme: {
    colors: {
      primary: 'var(--color-primary)',
      'primary-900': 'var(--color-primary-900)',
      'primary-100': 'var(--color-primary-100)',
      'primary-50': 'var(--color-primary-50)',
      accent: 'var(--color-accent)',
      'accent-hover': 'var(--color-accent-hover)',
      'gray-warm': 'var(--color-gray-warm)',
      'gray-100': 'var(--color-gray-100)',
      'gray-300': 'var(--color-gray-300)',
      'gray-600': 'var(--color-gray-600)',
      'gray-900': 'var(--color-gray-900)',
      steel: 'var(--color-steel)',
      graphite: 'var(--color-graphite)',
      panel: 'var(--color-panel)',
      surface: 'var(--color-surface)',
      canvas: 'var(--color-canvas)',
      ink: 'var(--color-ink)',
      'ink-muted': 'var(--color-ink-muted)',
      'surface-1': 'var(--color-surface-1)',
      'surface-2': 'var(--color-surface-2)',
      hairline: 'var(--color-hairline)',
      inquiry: 'var(--color-inquiry-cta)',
      'inquiry-hover': 'var(--color-inquiry-cta-hover)',
      success: 'var(--color-success)',
      warning: 'var(--color-warning)',
      error: 'var(--color-error)',
      info: 'var(--color-info)',
      disabled: 'var(--color-disabled-bg)',
      selected: 'var(--color-selected-bg)',
      invalid: 'var(--color-invalid-bg)',
      valid: 'var(--color-valid-bg)',
      overlay: 'var(--overlay-bg)',
      drawer: 'var(--drawer-bg)',
      modal: 'var(--modal-bg)',
    },
    fontFamily: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
    },
    fontSize: {
      display: 'var(--text-display)',
      heading: 'var(--text-heading)',
      subhead: 'var(--text-subhead)',
      body: 'var(--text-body)',
      caption: 'var(--text-caption)',
      small: 'var(--text-small)',
    },
    maxWidth: {
      page: 'var(--container-page)',
      content: 'var(--container-content)',
      readable: 'var(--container-readable)',
    },
    spacing: {
      section: 'var(--section-padding-block)',
      block: 'var(--space-block)',
      element: 'var(--space-element)',
      inline: 'var(--space-inline)',
      dock: 'var(--conversion-mobile-dock-height)',
      header: 'var(--header-height)',
    },
  },
  shortcuts: {
    btn: 'inline-flex items-center justify-center gap-2 font-semibold rounded-[var(--radius-button)] transition-colors duration-[var(--motion-duration-fast)] ease-[var(--motion-ease-standard)] min-h-[var(--a11y-min-touch-target)] focus:outline-none focus-visible:outline-2 focus-visible:outline-[var(--color-focus)] focus-visible:outline-offset-[var(--a11y-focus-offset)] disabled:opacity-[var(--state-disabled-opacity)] disabled:cursor-not-allowed text-caption tracking-[0.16px] no-underline hover:no-underline',
    'btn-primary':
      'btn bg-[var(--button-primary-bg)] text-white hover:bg-[var(--color-primary-hover)] px-5 py-3',
    'btn-inquiry':
      'btn bg-[var(--conversion-inquiry-cta-bg)] text-[var(--conversion-inquiry-cta-text)] hover:bg-[var(--conversion-inquiry-cta-hover-bg)] px-5 py-3 shadow-[var(--conversion-inquiry-cta-shadow)]',
    'btn-secondary':
      'btn bg-gray-900 text-white hover:bg-black px-4 py-3',
    'btn-outline':
      'btn border border-primary text-primary hover:bg-primary-50 px-5 py-3',
    'btn-quiet':
      'btn bg-white text-primary hover:bg-primary-50 px-4 py-3',
    'quote-cart-trigger': 'hidden fixed right-[var(--conversion-quote-cart-trigger-right)] bottom-[var(--conversion-quote-cart-trigger-bottom)] z-[var(--z-sticky)] bg-[var(--conversion-inquiry-cta-bg)] text-[var(--conversion-inquiry-cta-text)] w-[var(--conversion-quote-cart-trigger-size)] h-[var(--conversion-quote-cart-trigger-size)] rounded-[var(--radius-card)] border border-[var(--conversion-inquiry-cta-bg)] shadow-[var(--shadow-elevated)] items-center justify-center hover:bg-[var(--conversion-inquiry-cta-hover-bg)] transition-colors duration-[var(--motion-duration-fast)] ease-[var(--motion-ease-standard)]',
    'quote-cart-badge': 'absolute -top-1 -right-1 bg-gray-900 text-white text-xs w-[var(--conversion-quote-cart-badge-size)] h-[var(--conversion-quote-cart-badge-size)] rounded-[var(--radius-input)] flex items-center justify-center hidden',
    'section': 'py-[var(--section-padding-block)]',
    'container': 'max-w-[var(--container-page)] mx-auto px-4 sm:px-6 lg:px-8',
    'card': 'bg-[var(--card-bg)] rounded-[var(--radius-card)] border border-hairline p-6',
    'section-band': 'py-[var(--section-padding-block)] border-y border-hairline bg-surface-1',
    'section-heading': 'text-heading font-semibold leading-tight text-gray-900 tracking-normal',
    'metric-card': 'bg-[var(--card-bg)] border border-hairline rounded-[var(--radius-card)] p-5 shadow-[var(--shadow-card)]',
    'proof-card': 'bg-[var(--card-bg)] border border-hairline rounded-[var(--radius-card)] p-6 shadow-[var(--shadow-card)]',
    'product-card': 'bg-[var(--card-bg)] border border-hairline rounded-[var(--radius-card)] shadow-[var(--shadow-card)] overflow-hidden transition duration-[var(--motion-duration-base)] ease-[var(--motion-ease-standard)] hover:shadow-[var(--shadow-elevated)] hover:border-primary-100 no-underline hover:no-underline',
    'product-media-frame': 'bg-[var(--media-frame-bg)] border border-[var(--media-frame-border)] rounded-[var(--radius-card)] aspect-[var(--media-gallery-aspect)] overflow-hidden p-5',
    'product-media-image': 'w-full h-full object-contain group-hover:scale-103 transition-transform duration-[var(--motion-duration-base)] ease-[var(--motion-ease-standard)]',
    'quote-panel': 'bg-[var(--sidebar-bg)] border border-hairline rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-6',
    'conversion-panel': 'bg-[var(--conversion-sticky-sidebar-bg)] border border-hairline rounded-[var(--radius-card)] shadow-[var(--shadow-card)] p-6',
    'mobile-cta-dock': 'md:hidden fixed bottom-0 left-0 right-0 min-h-[var(--conversion-mobile-dock-height)] bg-[var(--conversion-mobile-dock-bg)] border-t border-hairline z-[var(--z-dock)] flex gap-2 px-4 py-3',
    'overlay-backdrop': 'fixed inset-0 bg-[var(--overlay-bg)] z-[var(--z-modal-backdrop)] hidden',
    'drawer-panel': 'fixed top-0 right-0 h-full w-full sm:w-[var(--conversion-quote-cart-width)] bg-[var(--drawer-bg)] border-l border-hairline z-[var(--z-drawer)] transform translate-x-full transition-transform duration-[var(--motion-duration-base)] ease-[var(--motion-ease-standard)] flex flex-col',
    'modal-shell': 'hidden fixed inset-0 z-[var(--z-modal)] items-center justify-center p-4',
    'modal-panel': 'box-border bg-[var(--modal-bg)] max-w-[var(--conversion-download-gate-width)] w-full p-6 relative border border-hairline rounded-[var(--radius-card)] shadow-[var(--shadow-elevated)]',
    'trust-reassurance': 'flex items-center gap-2 text-small text-[var(--conversion-trust-note-color)]',
    'rfq-progress': 'h-[var(--conversion-rfq-progress-height)] rounded-[var(--conversion-rfq-progress-radius)] bg-[var(--conversion-rfq-progress-track-bg)] overflow-hidden',
    'rfq-progress-value': 'h-full rounded-[var(--conversion-rfq-progress-radius)] bg-[var(--conversion-rfq-progress-active-bg)] transition-all duration-[var(--motion-duration-base)] ease-[var(--motion-ease-standard)]',
    'table-procurement': 'w-full text-left text-caption border-separate border-spacing-0',
    'table-surface': 'w-full max-w-full overflow-x-auto shadow-[var(--table-shadow-mask)] bg-[var(--table-bg)] border border-hairline',
    'table-header-cell': 'text-left px-[var(--table-cell-padding-x)] py-[var(--table-cell-padding-y)] text-caption font-semibold text-[var(--table-header-text)]',
    'table-cell': 'px-[var(--table-cell-padding-x)] py-[var(--table-cell-padding-y)] text-caption text-gray-600',
    'form-control': 'box-border w-full min-h-[var(--field-height-md)] border border-[var(--field-border)] border-b-[var(--field-border-hover)] bg-[var(--field-bg)] rounded-[var(--radius-input)] px-[var(--field-padding-x)] py-[var(--field-padding-y)] text-body text-gray-900 placeholder:text-gray-600 focus:outline-none focus:ring-2 focus:ring-[var(--color-focus)] focus:border-[var(--color-focus)] invalid:border-[var(--field-error-border)] disabled:bg-[var(--field-disabled-bg)] disabled:text-[var(--field-disabled-text)] disabled:opacity-[var(--state-disabled-opacity)] transition duration-[var(--motion-duration-fast)] ease-[var(--motion-ease-standard)]',
    'file-control': 'box-border w-full border border-[var(--field-border)] bg-[var(--field-bg)] rounded-[var(--radius-input)] px-[var(--field-padding-x)] py-2 text-body text-gray-600 file:mr-4 file:py-2 file:px-4 file:border-0 file:bg-[var(--file-input-button-bg)] file:text-[var(--file-input-button-text)] file:font-medium file:cursor-pointer focus:outline-none focus:ring-2 focus:ring-[var(--color-focus)]',
    'required-marker': 'text-[var(--field-required-marker-color)]',
    'conditional-field': 'transition-opacity duration-[var(--conditional-field-transition-duration)] ease-[var(--motion-ease-standard)]',
    'form-error-summary': 'rounded-[var(--radius-card)] border border-[var(--form-error-summary-border)] bg-[var(--form-error-summary-bg)] p-4 text-caption text-[var(--form-error-summary-text)]',
    'form-status-submitting': 'rounded-[var(--radius-input)] bg-[var(--form-status-submitting-bg)] px-3 py-2 text-small text-primary',
    'form-status-success': 'rounded-[var(--radius-input)] bg-[var(--form-status-success-bg)] px-3 py-2 text-small text-success',
    'form-status-failed': 'rounded-[var(--radius-input)] bg-[var(--form-status-failed-bg)] px-3 py-2 text-small text-error',
  },
});
